import time
from google import genai
from google.genai import types
from google.genai.errors import APIError
from config import settings
from tools.search_suppliers import SCHEMA as SEARCH_SCHEMA, execute as search_execute
from tools.compare_prices import SCHEMA as COMPARE_SCHEMA, execute as compare_execute
from tools.verify_supplier import SCHEMA as VERIFY_SCHEMA, execute as verify_execute
from tools.check_logistics import SCHEMA as LOGISTICS_SCHEMA, execute as logistics_execute

TOOL_REGISTRY = {
    "search_suppliers": search_execute,
    "compare_prices": compare_execute,
    "verify_supplier": verify_execute,
    "check_logistics": logistics_execute
}

ALL_TOOL_SCHEMAS = [SEARCH_SCHEMA, COMPARE_SCHEMA, VERIFY_SCHEMA, LOGISTICS_SCHEMA]

client = genai.Client(api_key=settings.GEMINI_API_KEY)

SYSTEM_PROMPT = """You are DealFlow, an autonomous B2B sourcing agent. Your job is to find the best suppliers for a buyer's request.

RULES:
- ALWAYS use tools to find data. NEVER make up prices, supplier names, or logistics info.
- Follow this order: search_suppliers first, then verify_supplier for top candidates, then compare_prices, then check_logistics.
- You may skip a tool if it's not relevant to the request, but never skip search.
- When presenting your final recommendation, use this format:

## Recommendation

| Rank | Supplier | Unit Price | Total Cost | Reliability | Est. Delivery |
|------|----------|-----------|------------|-------------|---------------|
| 1 | ... | ... | ... | ... | ... |

### Why Supplier #1
[Explain the reasoning — price, reliability, delivery tradeoffs]

### Tradeoffs to Consider
[Mention any risks or alternatives]

- Be specific with numbers. Reference actual data from your tool calls.
- If a tool returns an error, acknowledge it and work around it — don't pretend it succeeded."""

async def run_agent(messages: list[dict] = None) -> dict:
    if messages is None:
        messages = []
        
    trace = []
    
    gemini_messages = []
    for m in messages:
        if m["role"] == "user":
            gemini_messages.append(types.Content(role="user", parts=[types.Part.from_text(text=m["content"])]))
        elif m["role"] == "model":
            gemini_messages.append(types.Content(role="model", parts=[types.Part.from_text(text=m["content"])]))

    status = "completed"
    final_answer = ""
    step_count = 0
    
    try:
        for iter_count in range(6):
            response = client.models.generate_content(
                model=settings.GEMINI_MODEL,
                contents=gemini_messages,
                config=types.GenerateContentConfig(
                    system_instruction=SYSTEM_PROMPT,
                    tools=[{"function_declarations": ALL_TOOL_SCHEMAS}], 
                    temperature=0.0
                )
            )
            
            if not response.candidates:
                final_answer = "No response generated by AI."
                break
                
            candidate = response.candidates[0]
            
            if not candidate.content or not candidate.content.parts:
                final_answer = response.text or "No textual response generated."
                break
                
            has_func = False
            for p in candidate.content.parts:
                if p.function_call:
                    has_func = True
                    break
                    
            if has_func:
                gemini_messages.append(candidate.content)
                tool_response_parts = []
                
                for part in candidate.content.parts:
                    if part.function_call:
                        step_count += 1
                        fc = part.function_call
                        tool_name = fc.name
                        
                        tool_args = {}
                        if fc.args:
                            if hasattr(fc.args, 'items'):
                                tool_args = {k: v for k, v in fc.args.items()}
                            else:
                                tool_args = fc.args
                        
                        start_time = time.time()
                        try:
                            if tool_name in TOOL_REGISTRY:
                                tool_result = await TOOL_REGISTRY[tool_name](tool_args)
                            else:
                                tool_result = {"error": f"Tool {tool_name} not found"}
                        except Exception as e:
                            tool_result = {"error": str(e)}
                        
                        duration_ms = int((time.time() - start_time) * 1000)
                        
                        trace.append({
                            "step": step_count,
                            "tool": tool_name,
                            "input": tool_args,
                            "output": tool_result,
                            "duration_ms": duration_ms
                        })
                        
                        tool_response_parts.append(
                            types.Part.from_function_response(
                                name=tool_name,
                                response=tool_result
                            )
                        )
                gemini_messages.append(types.Content(role="user", parts=tool_response_parts))
            else:
                final_answer = response.text
                break
        else:
            status = "max_iterations_reached"
            
    except Exception as e:
        return {
            "answer": "I encountered an error contacting the AI service. Please try again.",
            "trace": trace,
            "status": "error"
        }
        
    return {
        "answer": final_answer,
        "trace": trace,
        "status": status
    }
